CREATE OR ALTER PROCEDURE [dbo].[SP_ANNEX7]
--DECLARE
	@DATE1 DATETIME ,
	@DATE2 DATETIME ,
	@DIV VARCHAR(5) = '%'
AS

/*
SELECT @DATE1 = '2019-07-17' , @DATE2 = '2025-12-30'
--*/

DROP TABLE IF EXISTS #TRNMAIN

SELECT PHISCALID FISCAL_YEAR, VCHRNO BILL_NO,BILLTO CUSTOMER_NAME,BILLTOTEL CUSTOMER_PAN,TRNDATE BILL_DATE,TAXABLE+NONTAXABLE+DCAMNT  AMOUNT,DCAMNT DISCOUNT,TAXABLE TAXABLE_AMOUNT,VATAMNT TAX_AMOUNT,TAXABLE+NONTAXABLE+VATAMNT  Total_Amount,'YES' IS_PRINTED,TRNTIME PRINTED_TIME,TRNUSER ETERED_BY,TRNUSER PRINTED_BY,TRNDATE AS EDATE,STAMP,DIVISION,PhiscalID, TRNMODE  
INTO #TRNMAIN
FROM RMD_TRNMAIN WITH (NOLOCK) 
WHERE VoucherType IN ('SI','TI','RE')
AND TRNDATE BETWEEN @DATE1 AND @DATE2
AND (@DIV = '%' OR DIVISION = @DIV)

CREATE CLUSTERED INDEX IX_CLS_OWUISHDFIUS ON #TRNMAIN (BILL_NO)


SELECT A.FISCAL_YEAR,A.BILL_NO,A.CUSTOMER_NAME,A.CUSTOMER_PAN,Convert(Varchar,A.Bill_Date,23) BILL_DATE,A.AMOUNT,A.DISCOUNT,A.TAXABLE_AMOUNT,A.TAX_AMOUNT,TOTAL_AMOUNT,A.IS_PRINTED,ISNULL(ACT.IS_ACTIVE,0) IS_ACTIVE,A.PRINTED_TIME,ISNULL(B.PRINTNOS,1) [PRINT NOS],A.ETERED_BY ,A.PRINTED_BY,Convert(Varchar,A.Edate,23) EDATE,A.Stamp,
ISNULL(X.SYNC_WITH_IRD,'NO') SYNC_WITH_IRD,ISNULL(X.ISREALTIME,'NO') ISREALTIME, A.TRNMODE Payment_Method, BOPI.VatRefund VAT_Refund_Amount, BOPI.PSO_TranId Transaction_Id
FROM #TRNMAIN A 
LEFT JOIN	(
			SELECT VCHRNO,COUNT(VCHRNO) + 1 PRINTNOS 
			FROM  tblPrintLog A WITH (NOLOCK)
			JOIN #TRNMAIN B ON A.VCHRNO = B.BILL_NO
			GROUP BY VCHRNO
			) B  ON A.BILL_NO = B.VCHRNO 
LEFT JOIN	(
			SELECT A.VCHRNO,
			CASE WHEN COALESCE(C.[STATUS], A.[STATUS], 2) = 0 THEN 'YES' ELSE 'NO' END SYNC_WITH_IRD,
			CASE WHEN COALESCE(C.[ISREALTIME], A.[IsRealTime], 0) = 0 THEN 'NO' ELSE 'YES' END ISREALTIME
			FROM TBLSYNCLOG A WITH (NOLOCK) 
			JOIN #TRNMAIN B ON A.VCHRNO = B.BILL_NO
			LEFT JOIN tblSyncLogStatus C WITH (NOLOCK) ON B.BILL_NO = C.VCHRNO
			) X ON A.BILL_NO = X.VCHRNO 
LEFT JOIN RMD_BillOnlinePaymentInfo BOPI WITH (NOLOCK) ON A.BILL_NO = BOPI.VCHRNO
LEFT JOIN	(
			SELECT BILL_NO , IIF(COUNT(MCODE) > 0 , 1 , 0) IS_ACTIVE
			FROM	(
					SELECT BILL_NO , MCODE , SUM(Quantity) Quantity 
					FROM	(
							SELECT B.BILL_NO,A.MCODE, A.Quantity 
							FROM RMD_TRNPROD A WITH (NOLOCK) 
							INNER JOIN #TRNMAIN B ON A.VCHRNO = B.BILL_NO
							UNION ALL
							SELECT C.BILL_NO,A.MCODE, - SUM(A.Quantity) Quantity 
							FROM RMD_TRNPROD A WITH (NOLOCK) 
							JOIN RMD_TRNMAIN B WITH (NOLOCK) ON A.VCHRNO = b.VCHRNO
							JOIN #TRNMAIN C ON B.REFBILL = C.BILL_NO
							GROUP BY A.MCODE , C.BILL_NO
							) X 
					GROUP BY BILL_NO , MCODE
					) A 
			WHERE Quantity <> 0
			GROUP BY BILL_NO
			) act ON A.BILL_NO = act.BILL_NO
ORDER BY A.BILL_DATE ASC

DROP TABLE IF EXISTS #TRNMAIN