IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JewelleryDetail') AND NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JewelleryDetail' AND COLUMN_NAME = 'luxuryNonTaxable')
alter table JewelleryDetail add luxuryNonTaxable DECIMAL(22,12)

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JewelleryDetail') AND NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JewelleryDetail' AND COLUMN_NAME = 'flatDiscount')
alter table JewelleryDetail add flatDiscount DECIMAL(22,12)