IF OBJECT_ID('DF_MULTIALTUNIT_RATE') IS NOT NULL
ALTER TABLE MULTIALTUNIT DROP CONSTRAINT DF_MULTIALTUNIT_RATE

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RATE' AND TABLE_NAME = 'MULTIALTUNIT' AND NUMERIC_PRECISION <> 22 AND NUMERIC_SCALE <> 12)
ALTER TABLE MULTIALTUNIT ALTER COLUMN RATE DECIMAL(22,12) NOT NULL


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'EnableFlatSRateInAltUnit' AND TABLE_NAME = 'SETTING')
ALTER TABLE SETTING ADD EnableFlatSRateInAltUnit TINYINT NOT NULL DEFAULT (0) WITH VALUES

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RATE_B' AND TABLE_NAME = 'MULTIALTUNIT')
ALTER TABLE MULTIALTUNIT ADD RATE_B DECIMAL(22,12) NOT NULL DEFAULT (0) WITH VALUES

