--CREATE OR ALTER PROC OSP_GetPurchaseOrderForPurchase
DECLARE
@supplier VARCHAR(25),
@Today DATE,
@DIVISION VARCHAR(20),
@ForGrn BIT = 0
--AS

SELECT @supplier = 'PA131', @Today = '2025-01-01', @DIVISION = 'SBP', @ForGrn = 0

DROP TABLE IF EXISTS #PURCHASEORDERS
DROP TABLE IF EXISTS #GRNRECEIPTS

-- Create temp table for purchase orders
SELECT OM.VCHRNO, OM.TRNAC, OM.DIVISION, OM.PhiscalID, OM.EXPDATE,
    OP.MCODE, OP.BC BARCODE, OP.RATE, ISNULL(TPS.CONFACTOR, 1) CONFACTOR, 
    OP.ALTRATE, OP.ALTUNIT, OP.REALRATE, OP.UNIT, OP.ALTQTY_IN PURCHASEORDEREDQTY,
    MI.DESCA, MI.MENUCODE, MI.REQEXPDATE EXPORT
INTO #PURCHASEORDERS FROM RMD_ORDERMAIN OM
    INNER JOIN RMD_ORDERPROD OP ON OM.VCHRNO = OP.VCHRNO
    LEFT JOIN RMD_TRNPROD_STATUS TPS ON OM.VCHRNO = TPS.VCHRNO AND OM.PhiscalID = TPS.PhiscalID AND OP.MCODE = TPS.MCODE AND OP.SNO = TPS.SNO
    LEFT JOIN MENUITEM MI ON OP.MCODE = MI.MCODE
    WHERE OM.TRNAC = @supplier AND ISNULL(OM.EXPDATE, @Today) >= @Today AND OM.DIVISION = @DIVISION

-- Create temp table for GRN receipts
SELECT * INTO #Receipts FROM(
    SELECT MCODE, BC, ALTUNIT, INVOICENO, DIVISION, SUM(ISNULL(ALTQTY_IN, 0)) RecieptQuantity FROM GRNPROD
    WHERE ISNULL(ALTQTY_IN, 0) >= 0 AND @ForGrn = 1
    GROUP BY MCODE, BC, ALTUNIT, INVOICENO, DIVISION
    UNION ALL
    SELECT MCODE, BC, ALTUNIT, INVOICENO, DIVISION, SUM(ISNULL(ALTQTY_IN, 0)-ISNULL(REALQTY,0))  RecieptQuantity FROM PURPROD 
    WHERE VCHRNO LIKE 'PI%' AND (ISNULL(REALQTY_IN,0)-ISNULL(REALQTY,0))>=0 AND @ForGrn = 0
    GROUP BY MCODE, BC, ALTUNIT, INVOICENO, DIVISION
) A

-- Final result
SELECT PO.VCHRNO, PO.TRNAC, PO.MCODE, PO.BARCODE, PO.DESCA, PO.MENUCODE, PO.RATE, 
       PO.CONFACTOR, PO.ALTRATE, PO.ALTUNIT, PO.REALRATE, PO.UNIT, PO.PURCHASEORDEREDQTY,
       ISNULL(GR.GOODSRECEIVEDQTY, 0) GOODSRECEIVEDQTY,
       (PO.PURCHASEORDEREDQTY - ISNULL(GR.GOODSRECEIVEDQTY, 0)) REMAININGQTY, 
       NULL WAREHOUSE, PO.EXPORT
FROM #PURCHASEORDERS PO
LEFT JOIN #GRNRECEIPTS GR ON PO.MCODE = GR.MCODE 
                           AND ISNULL(PO.BARCODE, '') = ISNULL(GR.BC, '') 
                           AND PO.ALTUNIT = GR.ALTUNIT 
                           AND PO.VCHRNO = GR.INVOICENO 
                           AND PO.DIVISION = GR.DIVISION
WHERE PO.PURCHASEORDEREDQTY > ISNULL(GR.GOODSRECEIVEDQTY, 0)
ORDER BY PO.VCHRNO, PO.MCODE

DROP TABLE IF EXISTS #PURCHASEORDERS
DROP TABLE IF EXISTS #GRNRECEIPTS