CREATE OR ALTER PROC OSP_GetSalesOrderForDelivery
--DECLARE @Customer VARCHAR(25)
AS
--SELECT @Customer = 'PA1'
DROP TABLE IF EXISTS #SALESORDERS
DROP TABLE IF EXISTS #DELIVERIES
DROP TABLE IF EXISTS #RETURNS

-- Create temp table for sales orders
SELECT OM.VCHRNO, OM.TRNAC, OM.DIVISION, OM.PhiscalID, OM.REMARKS, OM.TOTALFLATDISCOUNT,
       OP.MCODE, OP.BC BARCODE, OP.REALRATE, OP.ALTRATE, OP.ALTUNIT, OP.UNIT, 
       (OP.REALQTY - ISNULL(OP.REALQTY_IN, 0)) SALESORDEREDQTY,
       ISNULL(TPS.CONFACTOR, 1) CONFACTOR,
       IIF(OP.INDDISCOUNTRATE = 0 OR OP.INDDISCOUNTRATE IS NULL, 
           IIF(OP.AMOUNT = 0, 0, (OP.INDDISCOUNT / OP.AMOUNT) * 100), 
           OP.INDDISCOUNTRATE) INDDISCOUNTRATE,
       ISNULL(OP.FLATDISCOUNT, 0) FLATDISCOUNT,
       ISNULL(OP.INDDISCOUNT, 0) INDDISCOUNT
INTO #SALESORDERS
FROM RMD_ORDERMAIN OM
INNER JOIN RMD_ORDERPROD OP ON OM.VCHRNO = OP.VCHRNO 
LEFT JOIN RMD_TRNPROD_STATUS TPS ON OM.VCHRNO = TPS.VCHRNO 
AND OP.MCODE = TPS.MCODE AND OP.SNO = TPS.SNO
WHERE OM.VCHRNO LIKE 'SO%' AND OM.TRNAC = @Customer


-- Create temp table for deliveries
SELECT VCHRNO, MCODE, INVOICENO, DIVISION, SUM(ISNULL(REALQTY, 0) - ISNULL(REALQTY_IN, 0)) DELIVEREDQTY
INTO #DELIVERIES
FROM RMD_TRNPROD
WHERE VCHRNO LIKE 'DL%' AND (ISNULL(REALQTY, 0) - ISNULL(REALQTY_IN, 0)) >= 0 
AND INVOICENO IN (SELECT DISTINCT VCHRNO FROM #SALESORDERS)
GROUP BY VCHRNO, MCODE, INVOICENO, DIVISION



-- Create temp table for returns
SELECT MCODE, INVOICENO, DIVISION, SUM(ISNULL(REALQTY_IN, 0)) DELIVEREDRETURNEDQTY
INTO #RETURNS
FROM RMD_TRNPROD
WHERE VCHRNO LIKE 'DR%' AND (ISNULL(REALQTY_IN, 0) - ISNULL(REALQTY, 0)) >= 0
AND INVOICENO IN (SELECT DISTINCT VCHRNO FROM #DELIVERIES)
GROUP BY MCODE, INVOICENO, DIVISION

-- Final result
SELECT SO.VCHRNO, SO.TRNAC, SO.MCODE, SO.BARCODE, MI.DESCA, MI.MENUCODE, 
       SO.REALRATE RATE, SO.ALTRATE, SO.ALTUNIT, SO.CONFACTOR, SO.UNIT,
       ((SO.SALESORDEREDQTY + ISNULL(D.DELIVEREDRETURNEDQTY, 0)) - ISNULL(D.DELIVEREDQTY, 0)) REMAININGQTY,
       NULL WAREHOUSE, SO.REMARKS, SO.INDDISCOUNTRATE, SO.FLATDISCOUNT, SO.TOTALFLATDISCOUNT, 
       SO.INDDISCOUNT, ISNULL(D.DELIVEREDRETURNEDQTY, 0) DELIVEREDRETURNEDQTY
FROM #SALESORDERS SO
LEFT JOIN MENUITEM MI ON SO.MCODE = MI.MCODE
LEFT JOIN 
(
	SELECT D.MCODE, D.INVOICENO, D.DIVISION, SUM(DELIVEREDQTY) DELIVEREDQTY, SUM(R.DELIVEREDRETURNEDQTY) DELIVEREDRETURNEDQTY  FROM #DELIVERIES D
	LEFT JOIN #RETURNS R ON D.MCODE = R.MCODE AND D.VCHRNO = R.INVOICENO AND D.DIVISION = R.DIVISION
	GROUP BY D.MCODE, D.INVOICENO, D.DIVISION
)D ON SO.MCODE = D.MCODE AND SO.VCHRNO = D.INVOICENO AND SO.DIVISION = D.DIVISION
WHERE ((SO.SALESORDEREDQTY + ISNULL(D.DELIVEREDRETURNEDQTY, 0)) - ISNULL(D.DELIVEREDQTY, 0)) > 0
ORDER BY VCHRNO, MCODE

DROP TABLE IF EXISTS #SALESORDERS
DROP TABLE IF EXISTS #DELIVERIES
DROP TABLE IF EXISTS #RETURNS