CREATE OR ALTER PROC [dbo].[OSP_GetCounterOrderAdvance]
--DECLARE
@OrderNo VARCHAR(25),
@AdvanceAc VARCHAR(25)
AS
--SELECT @OrderNo = 'SO1191-KMT-82/83', @AdvanceAc  ='PA1'

DECLARE @AdvanceAmount NUMERIC(18,2), @FromDelivery BIT
DECLARE  @INVOICE TABLE(MCODE VARCHAR(25) NOT NULL PRIMARY KEY, Quantity NUMERIC(18,3))
DROP TABLE IF EXISTS #BILLS

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RMD_ORDER_DELIVERY') 
	INSERT INTO @INVOICE
	SELECT MCODE, SUM(QTY) Quantity FROM RMD_ORDER_DELIVERY
	WHERE VCHRNO = @OrderNo
	GROUP BY MCODE
ELSE 
	INSERT INTO @INVOICE
	SELECT TP.MCODE, SUM(TP.Quantity) Quantity FROM SALES_TRNMAIN TM 
	JOIN SALES_TRNPROD TP ON TM.VCHRNO = TP.VCHRNO 
	WHERE TM.REFORDBILL = @OrderNo
	GROUP BY TP.MCODE

SELECT VCHRNO INTO #BILLS FROM SALES_TRNMAIN WHERE REFORDBILL = @OrderNo

select @AdvanceAmount =  SUM(ATN.CRAMNT - ATN.DRAMNT) from  #BILLS AC
join RMD_TRNTRAN ATN on AC.VCHRNO = ATN.VCHRNO
WHERE ATN.A_ACID= @AdvanceAc

SELECT ISNULL(D.Flavour,'')Flavour,ISNULL(D.Design,'')Design,ISNULL(D.Shape,'')Shape,ISNULL(D.[Weight],'0')[Weight], D.CakeMessage, M.PhiscalID FISCALID,M.VCHRNO
, M.ORDERNO ORDNO, M.TRNDATE,M.NETAMNT, M.TRNTIME,ISNULL(M.MEMBERNO,'') MEMBERNO,M.DELIVERYDATE ESTIMATEDDELIVERY,M.REMARKS,M.TRNUSER,ISNULL(M.DELIVERYADDRESS,'')DELIVERYADDRESS, ISNULL(M.CHALANNO,'')CHALANNO, ISNULL(M.CustomerName,'')CustomerName,
ISNULL(M.MOBILENO,'')MOBILENO, IIF(M.STATUS = 8,ISNULL(@AdvanceAmount, 0),ISNULL(M.ADVANCE,0)) ADVANCE, M.TRNMODE, ISNULL(P.ITEMDESC,MT.DESCA) ITEMDESC, P.MCODE,ISNULL(P.BC,'')BC ,AC.ACID,AC.ACNAME,
AC.ADDRESS,AC.PHONE, P.ALTQTY - ISNULL(T.QUANTITY, 0) QUANTITY, P.ALTRATE RATE, (P.ALTQTY - ISNULL(T.QUANTITY, 0)) * P.ALTRATE AMOUNT, MT.DESCA,M.BILLTOADD, M.BILLTOTEL PANNo,
ISNULL(P.INDDISCOUNTRATE,0) INDDISRATE, M.DCRATE * 100 DCRATE, P.ALTUNIT,P.INDDISCOUNTRATE, CONVERT(INT, P.SNO) SNO
from RMD_ORDERMAIN M 
join RMD_ORDERPROD P on P.VCHRNO = M.VCHRNO 
Left JOIN RMD_Order_AdditionalDetail D on D.VCHRNO = M.VCHRNO and P.MCODE = D.MCODE
join MENUITEM MT on P.MCODE = MT.MCODE 
LEFT JOIN RMD_ACLIST AC ON M.TRNAC = AC.ACID
LEFT JOIN @INVOICE T ON P.MCODE = T.MCODE 
WHERE P.QUANTITY - isnull(T.Quantity, 0) > 0 AND M.VCHRNO LIKE 'SO%'AND M.VCHRNO  = @OrderNo