CREATE OR ALTER PROC OSP_GetStockDetail
--DECLARE
@JSON VARCHAR(MAX),
@DIVISION VARCHAR(3),
@PhiscalId VARCHAR(10),
@WAREHOUSE VARCHAR(50),
@VCHRNO VARCHAR(25) = ''
AS
--SET @JSON = '[{"MCODE": "M100"},{"MCODE": "M127118"},{"MCODE": "M127118", "WAREHOUSE":"Main Warehouse"},{"MCODE": "M2304"}]'; SET @DIVISION = 'MMX'; SET @PhiscalId = '81/82'; SET @WAREHOUSE = 'DefaultDeliveryWarehouse'
DECLARE @BCStock BIT
SELECT @BCStock = CONVERT(BIT,COALESCE(EnableBarcodeDetails,0)) FROM SETTING

SELECT P.MCODE, P.WAREHOUSE, IIF(@BCStock=1 OR M.PTYPE = 4, COALESCE(BC,''), '') BC, TRIM(COALESCE(BATCH,'')) BATCH, sum(realqty_in)-sum(realqty) STOCK from RMD_TRNPROD P WITH (NOLOCK) 
JOIN OPENJSON(@JSON) 
WITH
(
	MCODE VARCHAR(25) '$.MCODE',
	WAREHOUSE VARCHAR(50) '$.WAREHOUSE'
) D ON P.MCODE = D.MCODE AND P.WAREHOUSE = ISNULL( D.WAREHOUSE, @WAREHOUSE)
JOIN MENUITEM M ON D.MCODE = M.MCODE
WHERE PhiscalID = @PhiscalId and division = @DIVISION AND VCHRNO <> @VCHRNO --AND P.WAREHOUSE = @WAREHOUSE
GROUP BY P.MCODE, P.WAREHOUSE, COALESCE(BATCH,''),IIF(@BCStock=1 OR M.PTYPE = 4, COALESCE(BC,''), '')
HAVING sum(realqty_in)-sum(realqty) <> 0