CREATE OR ALTER PROC OSP_GetGRNListForPurchase
@PHISCALID VARCHAR(20),
@Supplier VARCHAR(25),
@DIVISION VARCHAR(20)
AS

DROP TABLE IF EXISTS #GRNITEMS
DROP TABLE IF EXISTS #PURCHASES

-- Create temp table for GRN items
SELECT TM.DIVISION, TM.PhiscalID, TM.VCHRNO, TM.TRNAC, TP.MCODE, TP.BC BARCODE, MI.DESCA, MI.MENUCODE, TP.RATE, ISNULL(TPS.CONFACTOR, 1) CONFACTOR, 
    TP.ALTRATE, TP.REALRATE, TP.ALTUNIT, TP.UNIT, SUM(TP.ALTQTY_IN - TP.ALTQTY) GOODSRECEIVEDQTY, TP.WAREHOUSE
INTO #GRNITEMS FROM GRNMAIN TM
INNER JOIN GRNPROD TP ON TM.VCHRNO = TP.VCHRNO 
INNER JOIN MENUITEM MI ON TP.MCODE = MI.MCODE
LEFT JOIN RMD_TRNPROD_STATUS TPS ON TM.VCHRNO = TPS.VCHRNO AND TP.MCODE = TPS.MCODE AND ISNULL(TP.BC, '') = ISNULL(TPS.BC, '') AND TP.SNO = TPS.SNO
WHERE TM.VOUCHERTYPE = 'GR' AND (TP.REALQTY_IN - TP.REALQTY) > 0 
    AND TM.PHISCALID = @PHISCALID AND TM.TRNAC = @Supplier AND TM.DIVISION = @DIVISION
GROUP BY TM.DIVISION, TM.PhiscalID, TM.VCHRNO, TM.TRNAC, TP.MCODE, TP.BC, 
    MI.DESCA, MI.MENUCODE, TP.REALRATE, TP.ALTUNIT, TP.WAREHOUSE, 
    TP.RATE, TP.UNIT, TPS.CONFACTOR, TP.ALTRATE, TP.ALTUNIT

-- Create temp table for purchases
SELECT MCODE, BC, ALTUNIT, INVOICENO, DIVISION, VOUCHERTYPE,
    SUM(IIF(VOUCHERTYPE = 'PI', ISNULL(ALTQTY_IN, 0), 0)) PURCHASEDQTY,
    SUM(IIF(VOUCHERTYPE != 'PI', 0, ISNULL(ALTQTY, 0))) PURCHASERETURNQTY,
    SUM(ISNULL(ALTQTY_IN, 0)- ISNULL(ALTQTY, 0)) TOTALPURCHASEDQTY
INTO #PURCHASES FROM PURPROD
WHERE VOUCHERTYPE IN ('PI', 'DN', 'PR') AND PHISCALID = @PHISCALID AND DIVISION = @DIVISION
GROUP BY MCODE, BC, ALTUNIT, INVOICENO, DIVISION, VOUCHERTYPE

-- Final result
SELECT G.VCHRNO, G.TRNAC, G.MCODE, G.BARCODE, G.DESCA, G.MENUCODE, G.RATE, G.CONFACTOR, G.ALTRATE, G.ALTUNIT, G.REALRATE, G.UNIT, G.GOODSRECEIVEDQTY,
    ISNULL(P.PURCHASEDQTY, 0) PURCHASEDQTY, ISNULL(P.PURCHASERETURNQTY, 0) PURCHASERETURNQTY,
    (G.GOODSRECEIVEDQTY - ISNULL(P.TOTALPURCHASEDQTY, 0)) REMAININGQTY, G.WAREHOUSE
FROM #GRNITEMS G
LEFT JOIN #PURCHASES P ON G.MCODE = P.MCODE 
    AND ISNULL(G.BARCODE, '') = ISNULL(P.BC, '') 
    AND G.ALTUNIT = P.ALTUNIT 
    AND G.VCHRNO = P.INVOICENO 
    AND G.DIVISION = P.DIVISION
WHERE G.TRNAC = @Supplier
    AND G.GOODSRECEIVEDQTY > ISNULL(P.TOTALPURCHASEDQTY, 0)
ORDER BY G.VCHRNO, G.MCODE

DROP TABLE IF EXISTS #GRNITEMS
DROP TABLE IF EXISTS #PURCHASES