IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'scannedLog')
CREATE TABLE scannedLog(
	logId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	trnDate DATE NOT NULL,
	trnTime VARCHAR(10) NOT NULL,
	trnUser VARCHAR(30) NOT NULL,
	sessionId int NOT NULL,
	entryNo INT NOT NULL,
	mcode varchar(25) NOT NULL,
	barcode varchar(50) NULL,
	unit varchar(50) NULL,
	quantity numeric(18, 3) NOT NULL,
	rate [decimal](20, 12) NOT NULL,
	--CONSTRAINT FK_ScannedLog_User FOREIGN KEY (trnUser) REFERENCES UserProfiles(UNAME),
	CONSTRAINT FK_ScannedLog_MenuItem FOREIGN KEY (mcode) REFERENCES MENUITEM(MCODE),
	CONSTRAINT FK_ScannedLog_Session FOREIGN KEY (sessionId) REFERENCES SESSION(SessionID),
);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'scannedLog' AND COLUMN_NAME = 'barcode')
ALTER TABLE scannedLog ADD barcode VARCHAR (50)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'scannedLog' AND COLUMN_NAME = 'unit')
ALTER TABLE scannedLog ADD unit VARCHAR (50)