CREATE OR ALTER VIEW vwContractPrice
AS
SELECT CP.CID, CP.CMID, CP.CUSTID, COALESCE(MG.MCODE, MI.MCODE, CP.ITEMCODE) ITEMCODE, COALESCE(MG.DESCA, MI.DESCA, CP.ITEMNAME) ITEMNAME, 
IIF(DISCOUNTTYPE = 'FLAT' AND FLATRATEDISCOUNT = 0, 0, CP.DISCOUNT) DISCOUNT, 
IIF(DISCOUNTTYPE = 'FLAT' AND FLATRATEDISCOUNT = 0, CP.DISCOUNT, FLATRATEDISCOUNT) FLATRATEDISCOUNT, CP.ISACTIVE, CP.DISCOUNTTYPE, CP.STAMP 
from CONTRACTPRICE CP LEFT JOIN MENUITEM MI ON CP.ITEMCODE = MI.PARENT AND MI.TYPE = 'A'
LEFT JOIN MENUITEM MG ON CP.ITEMCODE = MG.MGROUP