CREATE OR ALTER VIEW [dbo].[vwMemberProfile]  
AS  
SELECT MEMID CUSTID, MOBILE MOBILENO, TEL_R PHONE, CONCAT(FNAME, ' ' + NULLIF(LTRIM(RTRIM(MNAME)),''), ' ' + NULLIF(LTRIM(RTRIM(LNAME)),'')) CUSTNAME, IIF(IsMember = 1, COALESCE(NULLIF(BARCODE,''), MEMID),'') MEMBERNO
, COALESCE(NULLIF(T_STREET, ''), P_STREET)  [ADDRESS], PANNo, IdentityDocument, DocumentNo, AGE, GENDER, ACCOUNT CUSTACCOUNT, EMAIL, BARCODE, SCHEMEID, CustomerType, DOB, WAD, REFERENCEBY ReferredBy,ISMEMBER 
FROM MEMBERSHIP
WHERE Activate = 1