CREATE OR ALTER PROCEDURE [dbo].[NSP_ADDONS_REPORT]
--DECLARE
	@DATE1 DATE,
	@DATE2 DATE

AS

--SELECT @DATE1 = '2025-07-17', @DATE2 = '2026-04-24'

SET NOCOUNT ON;

DROP TABLE IF EXISTS #PRODDATA

SELECT A.VCHRNO , MCODE , MasterMcode
INTO #PRODDATA
FROM RMD_TRNPROD A WITH (NOLOCK)
JOIN RMD_TRNMAIN B WITH (NOLOCK) ON A.VCHRNO = B.VCHRNO
WHERE
	TRNDATE BETWEEN @DATE1 AND @DATE2
	AND A.VOUCHERTYPE IN ('SI','TI','CN')


DROP TABLE IF EXISTS #VCHRLIST

SELECT DISTINCT B.VCHRNO
INTO #VCHRLIST
FROM #PRODDATA B
JOIN #PRODDATA P ON P.VCHRNO = B.VCHRNO AND P.MCODE = B.MasterMcode
WHERE
	NULLIF(B.MasterMcode , '') LIKE 'M%'


DROP TABLE IF EXISTS #RESULT

SELECT T.VCHRNO , TRNDATE , BSDATE , RefGuid , P.MCODE , P.MasterMcode ,
CASE WHEN NULLIF(LTRIM(RTRIM(P.MasterMcode)), '') IS NULL THEN P.MCODE ELSE P.MasterMcode END AS ParentMCODE ,
P.ITEMDESC , P.Quantity , P.UNIT , P.RATE , P.AMOUNT , P.DISCOUNT , P.TAXABLE , T.NONTAXABLE , P.NETAMOUNT ,P.VAT , T.VOUCHERTYPE ,
ROW_NUMBER () OVER (PARTITION BY T.VCHRNO , REFGUID ORDER BY T.VCHRNO) SN ,
IIF(NULLIF(P.MASTERMCODE , '') IS NULL , 'A' ,'B') FLG , P.SNO
INTO #RESULT
FROM RMD_TRNPROD P WITH (NOLOCK)
JOIN RMD_TRNMAIN T WITH (NOLOCK) ON P.VCHRNO = T.VCHRNO
JOIN RMD_TRNPROD_STATUS PS WITH (NOLOCK) ON P.VCHRNO = PS.VCHRNO AND P.MCODE = PS.MCODE AND P.SNO = PS.SNO
JOIN #VCHRLIST V ON P.VCHRNO = V.VCHRNO
WHERE
	TRNDATE BETWEEN @DATE1 AND @DATE2
	AND T.VoucherType IN ('SI','TI' , 'CN')
	AND EXISTS	(
				SELECT 1 FROM #PRODDATA PD WHERE PD.VCHRNO = P.VCHRNO AND PD.MasterMcode IS NOT NULL AND PD.MasterMcode <> '' AND (PD.MasterMcode = P.MCODE or PD.MasterMcode = P.MasterMcode)
				)


DROP TABLE IF EXISTS #TOTAL
SELECT VCHRNO, ParentMCODE, RefGuid , SUM(AMOUNT) AS TOTAMOUNT, SUM(DISCOUNT) AS TOTDISCOUNT, SUM(TAXABLE) AS TOTTAXABLE, SUM(VAT) AS TOTVAT,
SUM(NONTAXABLE) AS TOTNONTAXABLE , SUM(NETAMOUNT) AS TOTNETAMOUNT
INTO #TOTAL
FROM #RESULT
GROUP BY VCHRNO, ParentMCODE, RefGuid


SELECT FORMAT(TRNDATE ,'MM-dd-yyyy') [Date] , BSDATE MITI , A.VCHRNO [Bill No] , B.DESCA [Main Item] ,
IIF(FLG = 'A' , '' , ITEMDESC) [Add On Items] , IIF(VOUCHERTYPE = 'CN' , Quantity * -1 , Quantity) [Sales Quantity] , Unit ,
IIF(FLG = 'A' , SUM(AMOUNT) OVER (PARTITION BY A.VCHRNO, A.PARENTMCODE , A.REFGUID ORDER BY A.VCHRNO) , NULL ) Rate ,
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN' , TOTAMOUNT * -1 , TOTAMOUNT) , NULL ) AMOUNT ,
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN' , TOTDISCOUNT * -1 , TOTDISCOUNT) , NULL ) [Discount Amount] ,
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN' , TOTTAXABLE * -1 , TOTTAXABLE) , NULL ) [Taxable Amount] ,
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN' , TOTVAT * -1 , TOTVAT) , NULL ) [Vatablle Amount] ,
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN' , TOTNONTAXABLE * -1 , TOTNONTAXABLE) , NULL ) [Non Taxable Amount],
IIF(FLG = 'A' , IIF(VOUCHERTYPE = 'CN', TOTNETAMOUNT * -1 , TOTNETAMOUNT) , NULL) [Net Amount], SN
FROM #RESULT A
JOIN #TOTAL T ON A.VCHRNO = T.VCHRNO AND A.ParentMCODE = T.ParentMCODE AND A.RefGuid = T.RefGuid
LEFT JOIN MENUITEM B ON A.ParentMCODE = B.MCODE
ORDER BY TRNDATE , A.VCHRNO , SNO , FLG , SN


SET NOCOUNT OFF;