CREATE OR ALTER PROCEDURE [dbo].[SP_CUSTOMER_ENTRY]
--DECLARE
	@DIV VARCHAR(3) = '%',
	@CUSTID VARCHAR(50) = '%'

AS

SET NOCOUNT ON


SELECT CUSTNAME [Name] , C.Address , C.PANNO [Pan No.] , C.MOBILENO [Mobile No.] , C.MEMBERNO  [Member No.] , D.NAME [Branch Name]
FROM CUSTOMERPROFILE C
LEFT JOIN MEMBERSHIP M ON C.MEMBERNO = M.MEMID
LEFT JOIN DIVISION D ON LEFT(CUSTID ,3) = D.INITIAL
WHERE
	(@DIV = '%' OR D.INITIAL = @DIV)
	AND (@CUSTID = '%' OR C.CUSTID = @CUSTID)

SET NOCOUNT OFF