CREATE OR ALTER PROCEDURE [dbo].[SP_CUSTOMER_ENTRY]
--DECLARE
	@DIVISION VARCHAR(3) = '%',
	@CUSTID VARCHAR(50) = '%'

AS

SET NOCOUNT ON


SELECT CUSTID, CUSTNAME [Name], C.Address, C.MOBILENO [Mobile No.], C.PANNO [Pan No.], C.MEMBERNO  [Member No.], M.REG_DATE [Reg. Date] , D.NAME [Branch Name]
FROM CUSTOMERPROFILE C
LEFT JOIN MEMBERSHIP M ON C.MEMBERNO = M.MEMID
LEFT JOIN DIVISION D ON LEFT(CUSTID ,3) = D.INITIAL
WHERE
	(@DIVISION = '%' OR D.INITIAL = @DIVISION)
	AND (@CUSTID = '%' OR C.CUSTID = @CUSTID)

SET NOCOUNT OFF