CREATE OR ALTER PROCEDURE [dbo].[RSP_TableOrders]
--DECLARE
@tableNo varchar(25)
as
set nocount on;
SELECT M.MENUCODE item_code, M.DESCA item_name, M.VAT vat, SUM(P.QUANTITY) quantity, M.RATE_A rate
    FROM RMD_KOTPROD P JOIN RMD_KOTMAIN_STATUS S ON P.KOTID = S.KOTID JOIN MENUITEM M ON P.MCODE = M.MCODE WHERE S.STATUS = 'ACTIVE' AND P.TABLENO = @tableNo
	GROUP BY M.MENUCODE, M.DESCA, M.VAT, M.RATE_A