CREATE OR ALTER   PROC [dbo].[OSP_GetReceipeConsumptionList]
--DECLARE 
@Warehouse VARCHAR(50), 
@VCHRNO VARCHAR(25)
AS
--SET @VCHRNO ='TI64-PKR-81/82'; SET @Warehouse = 'Main Warehouse'
DECLARE @ItemWiseWarehouse BIT, @AutoConsumeIntermediateRecipe BIT
SELECT @ItemWiseWarehouse = ItemWiseWarehouse, @AutoConsumeIntermediateRecipe = AutoConsumeIntermediateRecipe FROM SETTING

DROP TABLE IF EXISTS #RecipeDetail

SELECT A.MCODE ISSUENO,  TR.RMCODE MCODE,TR.PMCODE PMCODE,TR.SNO REFSNO, TR.SNO REFSERIAL, TR.IsPrimaryItem, C.BASEUNIT UNIT, C.BASEUNIT ALTUNIT, 
	S.REALQTY_IN * TR.QTY / A.FACTOR REALQTY_IN,
	S.RealQty * TR.QTY / A.FACTOR RealQty,
	S.Quantity * TR.QTY / A.FACTOR Quantity,
	IIF(ISNULL(C.CRATE, 0) > 0 , C.CRATE , C.PRATE_A) RATE,
	IIF(@ItemWiseWarehouse = 1 AND ISNULL(D.WHOUSE, '') <> '' , D.WHOUSE , @Warehouse ) WAREHOUSE, C.PTYPE,
	CONCAT('Recipe Consumption for ',D.DESCA,' (', D.MCODE, ')') Remarks
	INTO #RecipeDetail
	FROM  SALES_TRNPROD S
	INNER JOIN vwActiveRecipeMain A ON A.MCODE = S.MCODE
	join TRNPROD_RECEIPE TR ON A.ENO = TR.ENO AND S.VCHRNO = TR.VCHRNO AND S.SNO = TR.SNO
	INNER JOIN MENUITEM C ON tr.RMCODE = C.MCODE
	INNER JOIN MENUITEM D ON TR.PMCODE = D.MCODE
	WHERE A.FACTOR > 0 AND S.VCHRNO = @VCHRNO

SELECT ISSUENO, REFSNO, REFSERIAL, MCODE , IsPrimaryItem,UNIT, ALTUNIT, REALQTY_IN, REALQTY_IN ALTQTY_IN, RealQty, RealQty AltQty, Quantity, RATE, RATE REALRATE, RATE ALTRATE,
RATE * Quantity AMOUNT, WAREHOUSE, Remarks
FROM
(
	SELECT * FROM #RecipeDetail WHERE PTYPE NOT IN (2,5) OR @AutoConsumeIntermediateRecipe = 0
	UNION ALL
	SELECT TR.ISSUENO, B.RMCODE, A.MCODE, TR.REFSNO, TR.REFSNO, TR.IsPrimaryItem, C.BASEUNIT , C.BASEUNIT, 
	TR.REALQTY_IN * B.QTY / A.FACTOR REALQTY_IN,
	TR.RealQty * B.QTY / A.FACTOR RealQty,
	TR.Quantity * B.QTY / A.FACTOR Quantity,
	IIF(ISNULL(C.CRATE, 0) > 0 , C.CRATE , C.PRATE_A) RATE,
	IIF(@ItemWiseWarehouse = 1 AND ISNULL(C.WHOUSE, '') <> '' , C.WHOUSE , @Warehouse ) WAREHOUSE, C.PTYPE,
	CONCAT('Recipe Consumption for ',E.DESCA,' (', E.MCODE, ')') Remarks
    FROM vwActiveRecipeMain A INNER JOIN vwActiveRecipeProd B ON A.ENO = B.ENO
	JOIN (SELECT ISSUENO, MCODE, REFSNO, IsPrimaryItem, REALQTY_IN, RealQty, Quantity FROM #RecipeDetail WHERE PTYPE IN (2,5)) TR ON A.MCODE = TR.MCODE
    INNER JOIN MENUITEM C ON B.RMCODE = C.MCODE
    INNER JOIN MENUITEM E ON A.MCODE = E.MCODE
    WHERE A.FACTOR > 0 AND @AutoConsumeIntermediateRecipe = 1
) A